version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
